# theme = "monokai_pro_ristretto"
theme = "varua"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
";" = "command_mode"
esc = ["collapse_selection", "keep_primary_selection"]
